### ISSUE TITLE
Build a static website

### ISSUE THREAD

**Issue by RichardLitt** [opensourcecities/montreal#1]
Something we can point to. I think that osmontreal.ca would work well.

**Comment by RichardLitt** [comment]
I can't legally buy .ca domains! If someone else would like to: https://en.wikipedia.org/wiki/.ca#Canadian_Presence_Requirements. :)

**Comment by pestilencia** [comment]
Are you still up yo osmontreal.ca?  Or even fossmontreal.ca?
I can buy it.

**Comment by RichardLitt** [comment]
Perhaps we should use a different name than `.ca`, as there are now cities here which aren't in Canada. Maybe a global website for all of the lists?

**Comment by pestilencia** [comment]
Apparently `opensourcecities.com` and `.org` is taken. `opensourcecities.io` ?

**Comment by RichardLitt** [comment]
We may be putting the cart before the horse. I don't think there's an issue with `opensourcecities.github.com`, do you? Why don't we just use the default GitHub pages for this?

**Comment by pestilencia** [comment]
That's true. I thought you had a reason to not using github pages. Besides we can put custom domain, say `opensourcecities.io` on top of GH pages anyway. Slightly more cleaner domain.

**Comment by pestilencia** [comment]
+1

**Comment by TammyMackenzie** [comment]
If there is a webmaster, content, and login info, I can set up a basic wordpress page. Home, Contact, Blog, multi-lingual.

**Comment by RichardLitt** [comment]
Thanks @TammyMackenzie. I'm not sure that this needs to be on Wordpress; Jekyll should do fine.

**Comment by khos2ow** [comment]
or even Hugo (https://gohugo.io/)

**Comment by RichardLitt** [comment]
@khos2ow Want to PR a basic site? :)

**Comment by khos2ow** [comment]
@RichardLitt yeah sure, I'll try to submit a PR Soon&trade;! May be this weekend if I manage some time.

**Comment by RichardLitt** [comment]
No rush! That would be awesome. If you push incomplete work to a branch, @TammyMackenzie may be able to help, too. :)

**Comment by khos2ow** [comment]
@RichardLitt can you create another repository called **opensourcecities.github.io** under https://github.com/opensourcecities/ namespace?
That is needed to have https://opensourcecities.github.io in the first place.

**Comment by TammyMackenzie** [comment]
Here is the site. It needs 2 fixes right off the top: The link color is set at white and looks terrible. And it needs more info on open source.  https://drive.google.com/drive/folders/1yz3L18UOn9gZ7TycdxlZfAwudY8fIUGt?usp=sharing

**Comment by khos2ow** [comment]
Thank you @TammyMackenzie. I've created the site it #22 .

**Comment by RichardLitt** [comment]
Thank you, @TammyMackenzie! That is awesome. @khos2ow Did you use those files to inform your hugo work?

**Comment by khos2ow** [comment]
@RichardLitt unfortunately no. I was kinda finished with the Hugo version when @TammyMackenzie commented here.
