### ISSUE TITLE
Add a Rakefile for automatically templating out additions

### ISSUE THREAD

**Issue by RichardLitt** [opensourcecities/montreal#36]
Something like this would be great:

```
$ rake project title="Montreal" github="@opensourcecities" description="A website"
```

Instead of having to manually copy templates.

**Comment by khos2ow** [comment]
What kind of templates?

**Comment by RichardLitt** [comment]
The samples: https://github.com/opensourcecities/montreal/blob/master/data/sample-other.yml

**Comment by khos2ow** [comment]
That can be done directly with hugo command. Something like `hugo new user` (don't remember the syntax by heart now, but in this ball park)

I didn't add it anywhere in the doc because contributors need to have hugo installed, rather than copy/paste the file.

**Comment by RichardLitt** [comment]
Good points. Shell or rake (I think?) would mean that users wouldn't need to have Hugo installed; it's what I normally use with Jekyll sites.

**Comment by khos2ow** [comment]
I like this idea! I would say we should support all three to attract as many people as possible without enforcing them to install something in order to contribute:
1) Hugo (natively)
2) Rake (intermediate)
3) Bash (zero-dependency).

**Comment by RichardLitt** [comment]
Let's just set up a bash script, then. I think that's the easiest. :)

**Comment by khos2ow** [comment]
Great, I'll do something this week and most probably update contribution guide with Hugo and bash for now to see what other we can do for rake or something totally different.

**Comment by khos2ow** [comment]
No worries.
I know, me neither, so don't take me up on that :wink:

**Comment by khos2ow** [comment]
I added hugo binary to the repo and the topic on this issue isn't required anymore. The only way user can add content is `./binaries/hugo new <type>/<filename>.md`, in which type can be:

- organizations
- users
- projects
- incubators
- other
