### ISSUE TITLE
rickshaw's website breaks Travis

### ISSUE THREAD

**Issue by khos2ow** [opensourcecities/montreal#38]
Travis build fails because https://code.shutterstock.com/rickshaw/ doesn't exist anymore. Calling anyone from @Shutterstock org to clarify.

/cc @RichardLitt

**Comment by RichardLitt** [comment]
I've removed it. I would just remove it here, too. cc @cesine.

**Comment by cesine** [comment]
Hi guys, we are reworking our `code` site and it broke our links. @khos2ow here is the link for rickshaw docs https://shutterstock.github.io/rickshaw
