### ISSUE TITLE
Permalink of contents

### ISSUE THREAD

**Issue by khos2ow** [opensourcecities/montreal#43]
It would be cool to have a permalink of contents published on the site (orgs, users, ...). Something like:

- `https://opensourcecities.github.io/montreal/users/<name>`
- `https://opensourcecities.github.io/montreal/orgs/<name>`

This will give us the ability to have some kind of a _profile_ on the site and make the content shareable. To have this feature, I need to have a small-ish redesign of the hugo based site.

**Comment by khos2ow** [comment]
@RichardLitt @ruyadorno any suggestions, comments?

**Comment by RichardLitt** [comment]
This sounds good to me! Would be cool if people could fill out more information about themselves, too, in a text field that would then be rendered. I like this!

**Comment by ruyadorno** [comment]
👍 sounds good to me too!

**Comment by khos2ow** [comment]
Awesome! I'll open a PR and we can follow the discussion there. Soon&trade;!
